// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eojHsTxh2CznYQUhCcvLfa
// Component: pIRLaRVUlPAY
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import AdditionalSeoData from "../../AdditionalSeoData"; // plasmic-import: qJYR5wLO6ptv/component
import DummyWpContainer from "../../DummyWpContainer"; // plasmic-import: LgX6if24X2q3/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import DummyWpFooter from "../../DummyWpFooter"; // plasmic-import: Ou4WpcxmNsUe/component
import { useScreenVariants as useScreenVariantsngPcOWd604O } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: NGPcOWd-604O/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: eojHsTxh2CznYQUhCcvLfa/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: pIRLaRVUlPAY/css

createPlasmicElementProxy;

export const PlasmicAbout__VariantProps = new Array();

export const PlasmicAbout__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAbout__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsngPcOWd604O()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAbout.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAbout.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAbout.pageMetadata.title}
        />

        <meta
          key="description"
          name="description"
          content={PlasmicAbout.pageMetadata.description}
        />

        <meta
          key="og:description"
          property="og:description"
          content={PlasmicAbout.pageMetadata.description}
        />

        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicAbout.pageMetadata.description}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAbout.pageMetadata.ogImageSrc}
        />

        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicAbout.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <AdditionalSeoData
            data-plasmic-name={"additionalSeoData"}
            data-plasmic-override={overrides.additionalSeoData}
            className={classNames("__wab_instance", sty.additionalSeoData)}
          />

          <DummyWpContainer
            data-plasmic-name={"dummyWpContainer"}
            data-plasmic-override={overrides.dummyWpContainer}
            className={classNames("__wab_instance", sty.dummyWpContainer)}
            querydata={(() => {
              try {
                return $ctx.query.item;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"contents"}
              data-plasmic-override={overrides.contents}
              hasGap={true}
              className={classNames(projectcss.all, sty.contents)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"contentHeader"}
                data-plasmic-override={overrides.contentHeader}
                hasGap={true}
                className={classNames(projectcss.all, sty.contentHeader)}
              >
                <PlasmicImg__
                  data-plasmic-name={"headingSvg"}
                  data-plasmic-override={overrides.headingSvg}
                  alt={""}
                  className={classNames(sty.headingSvg)}
                  displayHeight={"317px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"30px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_dummy_wp_version/images/image2.svg",
                    fullWidth: 30.258,
                    fullHeight: 311.672,
                    aspectRatio: 0.097083
                  }}
                />

                <Stack__
                  as={"div"}
                  data-plasmic-name={"content"}
                  data-plasmic-override={overrides.content}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.content)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gjUb7
                    )}
                  >
                    {"WHO ARE WE?"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hvyG8,
                      hasVariant(globalVariants, "screen", "bp862")
                        ? "about-para"
                        : undefined
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "we are a bunch of internet enthusiasts, working with "
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-OHS4W3jM4QS0)" }}
                      >
                        {"WordPress"}
                      </span>
                      <React.Fragment>
                        {
                          " for the past 8years who started dummywp to give back to our community and make it easier for people to "
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-OHS4W3jM4QS0)" }}
                      >
                        {"try"}
                      </span>
                      <React.Fragment>
                        {" & test WordPress for "}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-OHS4W3jM4QS0)" }}
                      >
                        {"FREE"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <div
                      data-plasmic-name={"text4"}
                      data-plasmic-override={overrides.text4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text4,
                        hasVariant(globalVariants, "screen", "bp862")
                          ? "about-para2"
                          : undefined
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-VWmG8yuRh7sg)" }}
                        >
                          {
                            "some of our other groundbreaking public products for WordPress includes "
                          }
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.link__bdM4W
                            )}
                            component={Link}
                            href={"https://digits.unitedover.com/"}
                            platform={"nextjs"}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-VWmG8yuRh7sg)" }}
                              >
                                {"Digits"}
                              </span>
                            </React.Fragment>
                          </PlasmicLink__>
                        }

                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-VWmG8yuRh7sg)" }}
                        >
                          {" and "}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.link__u9Zbl
                            )}
                            component={Link}
                            href={"https://wpnotif.unitedover.com/"}
                            platform={"nextjs"}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-VWmG8yuRh7sg)" }}
                              >
                                {"WPNotif"}
                              </span>
                            </React.Fragment>
                          </PlasmicLink__>
                        }

                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </Stack__>
              </Stack__>
              <div
                data-plasmic-name={"contentFooter"}
                data-plasmic-override={overrides.contentFooter}
                className={classNames(projectcss.all, sty.contentFooter)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__btXyI
                  )}
                >
                  {"UNITEDOVER, LLC"}
                </div>
              </div>
            </Stack__>
            <Embed
              data-plasmic-name={"embedHtml"}
              data-plasmic-override={overrides.embedHtml}
              className={classNames("__wab_instance", sty.embedHtml)}
              code={
                "<style>\r\n  .about-para{\r\n    font-size:calc(22px + 12 * ((100vw - 320px)/ 543));\r\n  }\r\n\r\n  .about-para2{\r\n    font-size:  calc(20px + 7 * ((100vw - 320px)/ 543));\r\n  }\r\n</style>"
              }
            />
          </section>
          <DummyWpFooter
            data-plasmic-name={"dummyWpFooter"}
            data-plasmic-override={overrides.dummyWpFooter}
            className={classNames("__wab_instance", sty.dummyWpFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "additionalSeoData",
    "dummyWpContainer",
    "section",
    "contents",
    "contentHeader",
    "headingSvg",
    "content",
    "freeBox",
    "text4",
    "contentFooter",
    "embedHtml",
    "dummyWpFooter"
  ],

  additionalSeoData: ["additionalSeoData"],
  dummyWpContainer: ["dummyWpContainer"],
  section: [
    "section",
    "contents",
    "contentHeader",
    "headingSvg",
    "content",
    "freeBox",
    "text4",
    "contentFooter",
    "embedHtml"
  ],

  contents: [
    "contents",
    "contentHeader",
    "headingSvg",
    "content",
    "freeBox",
    "text4",
    "contentFooter"
  ],

  contentHeader: ["contentHeader", "headingSvg", "content", "freeBox", "text4"],
  headingSvg: ["headingSvg"],
  content: ["content", "freeBox", "text4"],
  freeBox: ["freeBox", "text4"],
  text4: ["text4"],
  contentFooter: ["contentFooter"],
  embedHtml: ["embedHtml"],
  dummyWpFooter: ["dummyWpFooter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    additionalSeoData: makeNodeComponent("additionalSeoData"),
    dummyWpContainer: makeNodeComponent("dummyWpContainer"),
    section: makeNodeComponent("section"),
    contents: makeNodeComponent("contents"),
    contentHeader: makeNodeComponent("contentHeader"),
    headingSvg: makeNodeComponent("headingSvg"),
    content: makeNodeComponent("content"),
    freeBox: makeNodeComponent("freeBox"),
    text4: makeNodeComponent("text4"),
    contentFooter: makeNodeComponent("contentFooter"),
    embedHtml: makeNodeComponent("embedHtml"),
    dummyWpFooter: makeNodeComponent("dummyWpFooter"),
    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "dummywp | About Us",
      description:
        "Create free WordPress staging site where you can upload your own plugin and theme to test out things before you make it live on your main site.",
      ogImageSrc:
        "https://site-assets.plasmic.app/70bd5841dbee59b55a44fb215e176a76.png",
      canonical: ""
    }
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
